---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-applications
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: applications
    repoURL: https://github.com/astrojerms/argocd-build-platform.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
