---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    path: applications/gitea
    repoURL: https://github.com/astrojerms/argocd-build-platform.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
