
---
apiVersion: v2
name: cert-manager
description: Helm chart to include loki with values
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
