
---
apiVersion: v2
name: minio
description: Helm chart to include ingress-nginx with values
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: ingress-nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
