
---
apiVersion: v2
name: minio
description: Helm chart to include loki with values
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: minio-operator
    version: 5.1.0
    repository: https://operator.min.io
    condition: minio.enabled
